### PR TITLE
Fix returned payload when cached from execution client

### LINKED ISSUE #5: Make sure ExecutionPayload is being returned correctly from proposeBlindedBlock
Reported from Sean in discord:

The big outstanding issue I'm having is that the initial payload header response from MEV-boost is something like this:
```
{
  "jsonrpc": "2.0",
  "result": {
    "parentHash": "0x29c12a5f851fa137cc967b8e7084605a9b2b0f3b92d7bc4ae05ac3158f5fd38d",
    "feeRecipient": "0x0000000000000000000000000000000000000001",
    "stateRoot": "0x1014a93b39908122be4202db72ba66cf287be6c6820473f5ad62cc67d1692407",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "random": "0x29c12a5f851fa137cc967b8e7084605a9b2b0f3b92d7bc4ae05ac3158f5fd38d",
    "blockNumber": "0x1",
    "gasLimit": "0x1c9c380",
    "gasUsed": "0x0",
    "timestamp": "0x61ba2559",
    "extraData": "0x",
    "baseFeePerGas": "0x7",
    "blockHash": "0x4fe17cc83472a6887c9216b04c4cc7fb2c8a1f99f94fdc239fe7e0007e62f6db",
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
  },
  "error": null,
  "id": 1
}
```

But the ExecutionPayload that's returned by proposeBlindedBlock looks like this:

```
{
  "jsonrpc": "2.0",
  "result": {
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "feeRecipient": "0x0000000000000000000000000000000000000000",
    "stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "receiptsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "logsBloom": "0x",
    "random": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "blockNumber": "0x0",
    "gasLimit": "0x0",
    "gasUsed": "0x0",
    "timestamp": "0x0",
    "extraData": "0x",
    "baseFeePerGas": null,
    "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "transactionsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000"
  },
  "error": null,
  "id": 1
}
```

Looks like everything is zeroed out, baseFeePerGas is null, which we can't parse, and there's a transactionsRoot as opposed to a transactions array

### PR DESCRIPTION
**Pull request by jparyani**
Fixes #5

### CODE REVIEW

File: lib/store.go [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+	payloads map[common.Hash]*ExecutionPayloadWithTxRootV1
+}
+
+// NewStore creates an in-mem store
+func NewStore() Store {
+	return &store{map[common.Hash]*ExecutionPayloadWithTxRootV1{}}
+}
+
+func (s *store) Get(blockHash common.Hash) *ExecutionPayloadWithTxRootV1 {
+	payload, ok := s.payloads[blockHash]
```
Comment (terencechain) [inline lib/store.go:25]: Do we need to have locks around these for concurrency?

Comment (jparyani) [reply lib/store.go:25]: Good catch, thanks! Fixed in https://github.com/flashbots/mev-boost/commit/c7be3e608b3b3979e724620455253a9fbf969c1b
